import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from qdrant_client import QdrantClient
from qdrant_client.http import models
import google.generativeai as genai

app = FastAPI(title="MYMY-IA-Magique Advanced AI Engine", version="2.0")

# إعداد مفتاح الذكاء الاصطناعي (Gemini)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

    # إعداد Qdrant
    QDRANT_HOST = os.getenv("QDRANT_HOST", "localhost")
    QDRANT_PORT = int(os.getenv("QDRANT_PORT", 6333))

    try:
        client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
        except Exception as e:
            client = None

            class DataItem(BaseModel):
                id: int
                    text: str
                        category: str
                            metadata: dict = {}

                            class SearchQuery(BaseModel):
                                query_text: str
                                    limit: int = 5

                                    @app.get("/")
                                    def read_root():
                                        return {
                                                "status": "Online", 
                                                        "message": "MYMY-IA-Magique AI Engine 2.0 is running with Cloud & Gemini integration!"
                                                            }

                                                            @app.post("/api/store")
                                                            def store_data(item: DataItem):
                                                                if not client:
                                                                        raise HTTPException(status_code=500, detail="Qdrant client is not initialized")
                                                                            
                                                                                collection_name = "mymy_erp_memory"
                                                                                    
                                                                                        collections = [col.name for col in client.get_collections().collections]
                                                                                            if collection_name not in collections:
                                                                                                    client.create_collection(
                                                                                                                collection_name=collection_name,
                                                                                                                            vectors_config=models.VectorParams(size=4, distance=models.Distance.COSINE)
                                                                                                                                    )
                                                                                                                                        
                                                                                                                                            dummy_vector = [0.1, 0.2, 0.3, 0.4]
                                                                                                                                                
                                                                                                                                                    client.upsert(
                                                                                                                                                            collection_name=collection_name,
                                                                                                                                                                    points=[
                                                                                                                                                                                models.PointStruct(
                                                                                                                                                                                                id=item.id,
                                                                                                                                                                                                                vector=dummy_vector,
                                                                                                                                                                                                                                payload={"text": item.text, "category": item.category, "metadata": item.metadata}
                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                            return {"success": True, "message": "Data stored successfully in vector memory", "id": item.id}

                                                                                                                                                                                                                                                            @app.post("/api/search")
                                                                                                                                                                                                                                                            def search_data(search: SearchQuery):
                                                                                                                                                                                                                                                                if not client:
                                                                                                                                                                                                                                                                        raise HTTPException(status_code=500, detail="Qdrant client is not initialized")
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                collection_name = "mymy_erp_memory"
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                collections = [col.name for col in client.get_collections().collections]
                                                                                                                                                                                                                                                                                                        if collection_name not in collections:
                                                                                                                                                                                                                                                                                                                    return {"results": [], "message": "Collection not found, please store data first"}
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                    records, _ = client.scroll(
                                                                                                                                                                                                                                                                                                                                                collection_name=collection_name,
                                                                                                                                                                                                                                                                                                                                                            limit=search.limit,
                                                                                                                                                                                                                                                                                                                                                                        with_payload=True,
                                                                                                                                                                                                                                                                                                                                                                                    with_vectors=False
                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                            matched_results = []
                                                                                                                                                                                                                                                                                                                                                                                                                    context_texts = []
                                                                                                                                                                                                                                                                                                                                                                                                                            for record in records:
                                                                                                                                                                                                                                                                                                                                                                                                                                        payload = record.payload
                                                                                                                                                                                                                                                                                                                                                                                                                                                    text_content = payload.get("text", "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if search.query_text.lower() in text_content.lower():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                matched_results.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "id": record.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "text": text_content,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "category": payload.get("category"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "metadata": payload.get("metadata")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                context_texts.append(text_content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # توليد تحليلي ذكي باستخدام Gemini إذا كان المفتاح متوفراً
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ai_summary = "Gemini API key not configured."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if GEMINI_API_KEY and context_texts:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model = genai.GenerativeModel('gemini-1.5-flash')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            prompt = f"بناءً على البيانات التالية المسترجعة من النظام:\n" + "\n".join(context_texts) + f"\n\nأجب عن استعلام المستخدم التالي باحترافية: {search.query_text}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            response = model.generate_content(prompt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ai_summary = response.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as ai_err:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ai_summary = f"AI Generation error: {str(ai_err)}"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "success": True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "query": search.query_text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "results_count": len(matched_results),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "results": matched_results,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "ai_insights": ai_summary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise HTTPException(status_code=500, detail=f"Search error: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            