                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import os
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from fastapi import FastAPI, HTTPException
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from pydantic import BaseModel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import google.generativeai as genai

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app = FastAPI(title="MYMY-IA-Magique", version="2.0")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if GEMINI_API_KEY:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        genai.configure(api_key=GEMINI_API_KEY)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class SearchQuery(BaseModel):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            query_text: str

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.get("/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def read_root():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {"status": "Online", "message": "MYMY-IA-Magique AI Engine is live and ready!"}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.post("/api/ai-chat")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def ai_chat(search: SearchQuery):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    insights = "Gemini API key not configured or missing."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if GEMINI_API_KEY:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model = genai.GenerativeModel('gemini-1.5-flash')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res = model.generate_content(search.query_text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    insights = res.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        insights = f"AI error: {str(e)}"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {"success": True, "query": search.query_text, "ai_response": insights}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                import uvicorn
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    port = int(os.environ.get("PORT", 10000))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        uvicorn.run("backend.main:app", host="0.0.0.0", port=port)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          